version: "3.7"

services:

  samba:
    image: dperson/samba
    restart: always
    command: '-u "pi;password" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no" -s "files;/files;yes;no" -s "movies;/movies;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Mexico_City
    ports:
      - 139:139
      - 445:445
    volumes:
      - ${MEDIA}:/media
      - ${MOVIES}:/movies
      - ${FILES}:/files
      - ${STORAGE}/torrents:/downloads

  plex:
    image: jaymoulin/plex:1.40.3.8555  #jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    # ports:
    #  - 32400:32400
    #  - 33400:33400
    environment:
      - TZ=America/Mexico_City
    volumes:
      - ${STORAGE}/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${MOVIES}:/movies
      - ${STORAGE}/tmp:/tmp
    restart: unless-stopped
    network_mode: "host" # Solo funciona en Linux

  transmission:
    image : jaymoulin/transmission:3.00-1.6.1
    command: transmission-daemon -f -g /config
    volumes:
      - ./transmission:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped
